config/routes.rb
EasyGym::Application.routes.draw do

  get "profile/:id",to: "users#profile", as: "profile", path_names: { profile: 'kalle' }
  devise_for :users

  get "home/index"

  resources :workout_sessions
  resources :statistics, only: [:index]
    resources :workouts
    resources :exercises

  root :to => 'home#index'

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :workout_sessions
  has_many :workout_exercises
  has_many :exercises, through: :workout_exercises

  accepts_nested_attributes_for :exercises, :allow_destroy => true
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @workout = Workout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/new
  # GET /workouts/new.json
  def new
    @workout = Workout.new
    @exercises = Exercise.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/1/edit
  def edit
    @workout = Workout.find(params[:id])
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(params[:workout])
    @exercises = Exercise.find(params[:exercise][:id])
    @workout.exercises << @exercises

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workouts_path, notice: 'workout was successfully created.' }
        format.json { render json: @workout, status: :created, location: @workout }
      else
        format.html { render action: "new" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workouts/1
  # PUT /workouts/1.json
  def update
    @workout = Workout.find(params[:id])

    respond_to do |format|
      if @workout.update_attributes(params[:workout])
        format.html { redirect_to @workout, notice: 'workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout = workout.find(params[:id])
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="input-field col s6">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="input-field col s6">
    <%= collection_select(:exercise, :id, @exercises, :id, :name, :prompt => 'Choose your exercise') %>
    <label>Exercise</label>
    
    <%= react_component 'Exercise', 
      { exercise: @exercises.first.name} %>
  
  </div>
</div>

<div class="row">
  <div class="input-field col s12">
    <%= f.label :description %>
    <%= f.text_area :description, class: "materialize-textarea" %>
  </div>
</div>

<div class="waves-effect waves-light">
    <%= f.submit "Add",class: "btn cyan darken-3" %>
</div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h2 class="center">Workouts</h2>

<table class="hoverable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Nr of exercises</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @workouts.each do |wo| %>
  <tr>
    <td><%= wo.name %></td>
    <td><%= wo.exercises.count %>
    <td><%= wo.description %></td>
    <td><%= link_to 'Show', wo, class: "waves-effect waves-light btn blue-grey darken-3"%></td>
    <td><%= link_to 'Edit', edit_workout_path(wo), class: "waves-effect waves-light btn lime darken-3" %></td>
    <td><%= link_to 'Destroy', wo, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn pink darken-3" %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Workout', new_workout_path, class: "btn cyan darken-3" %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path, class: "waves-effect waves-grey btn-flat" %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @workout.name %>
</p>

<p>
  <b>Description:</b>
  <%= @workout.description %>
</p>

<table class="hoverable">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Name</th>
      <th>Sets x Reps</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @workout.exercises.each do |exercise| %>
  <tr>
    <td><i class="medium mdi-action-accessibility cyan darken-3 circle" style="color:white;"></i></td>
    <td><%= exercise.name %></td>
    <td><%#= exercise.cycles.first.sets %>x<%#= exercise.cycles.first.resps %></td>
    <td><%= exercise.description %></td>
    <td><%#= exercise.picture %></td>
    <td><%= link_to 'Show', exercise, class: "waves-effect waves-light btn blue-grey darken-3" %></td>
    <td><%= link_to 'Edit', edit_exercise_path(exercise), class: "waves-effect waves-light btn lime darken-3" %></td>
    <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn pink darken-3" %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', exercises_path %>