config/routes.rb
EasyGym::Application.routes.draw do

  get "profile/:id",to: "users#profile", as: "profile", path_names: { profile: 'kalle' }
  devise_for :users

  get "home/index"

  resources :workout_sessions
  resources :statistics, only: [:index]
    resources :workouts
    resources :exercises

  root :to => 'home#index'

end

app/models/workout_session.rb
class WorkoutSession < ActiveRecord::Base
  attr_accessible :performed_at, :workout_id

  belongs_to :workout

end

app/controllers/workout_sessions_controller.rb
class WorkoutSessionsController < ApplicationController

  def index
    @workout_sessions = WorkoutSession.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
    @workout_session = WorkoutSession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workout_session }
    end
  end

  # GET /workout_sessions/new
  # GET /workout_sessions/new.json
  def new
    @workout_session = WorkoutSession.new
    @workouts = Workout.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workout_session }
    end
  end

  # GET /workout_sessions/1/edit
  def edit
    @workout_session = WorkoutSession.find(params[:id])
  end

  # POST /workout_sessions
  # POST /workout_sessions.json
  def create
    @workout_session = WorkoutSession.new(params[:workout_session])

    respond_to do |format|
      if @workout_session.save
        format.html { redirect_to workout_sessions_path, notice: 'workout_session was successfully created.' }
        format.json { render json: @workout_session, status: :created, location: @workout_session }
      else
        format.html { render action: "new" }
        format.json { render json: @workout_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workout_sessions/1
  # PUT /workout_sessions/1.json
  def update
    @workout_session = WorkoutSession.find(params[:id])

    respond_to do |format|
      if @workout_session.update_attributes(params[:workout_session])
        format.html { redirect_to @workout_session, notice: 'workout_session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workout_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_sessions/1
  # DELETE /workout_sessions/1.json
  def destroy
    @workout_session = WorkoutSession.find(params[:id])
    @workout_session.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/workout_sessions_helper.rb
module WorkoutSessionsHelper
end

app/views/workout_sessions/_form.html.erb
<%= form_for(@workout_session) do |f| %>

<div class="row">
  <div class="datepicker col s6">
    <%= f.label :performed_at %>
    <%= f.text_field :performed_at, type: "date", class: "datepicker" %>
  </div>
  <div class="input-field col s6">
    <%= f.collection_select :workout_id , Workout.all, :id, :name, :prompt => 'Choose your workout'%>
    <label>Exercise</label>
  </div>
</div>


<div class="waves-effect waves-light">
    <%= f.submit "Add",class: "btn cyan darken-3" %>
</div>
<% end %>

<script>
$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/workout_sessions/index.html.erb
<h4>WO sessions#index </h4>

<%= link_to 'New Session', new_workout_session_path, class: "btn cyan darken-3" %>

app/views/workout_sessions/new.html.erb
<h1>New Session</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_sessions_path, class: "waves-effect waves-grey btn-flat" %>