config/routes.rb
EasyGym::Application.routes.draw do

  get "profile/:id",to: "users#profile", as: "profile", path_names: { profile: 'kalle' }
  devise_for :users

  get "home/index"

  resources :workout_sessions
  resources :statistics, only: [:index]
    resources :workouts
    resources :exercises

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/home/_signup_form.html.erb
<%= form_for resource, :as => resource_name, :url => registration_path(resource_name) do |f| %>
  <%= devise_error_messages! %>

<div class="row">
  <div class="input-field col s4">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="input-field col s4">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="input-field col s4">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
</div>

<div class="row">
  <div class="input-field col s6">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="input-field col s6">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
</div>
  <div><%= f.submit "Sign up",class: "btn cyan darken-3" %></div>
<% end %>

app/views/home/index.html.erb
  <div class="parallax-container" style="width:100%;">
    <div class="parallax"><%=image_tag "img7.png", style: "width: 100%;"%></div>
  </div>
  <div class="section white z-depth-2">
    <div class="row container center">
      <div class="col s4 ">
        <i class="large mdi-av-playlist-add" style="color:#00838f;"></i>
        <h4 class="header">Add your workouts</h4>
        <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
      </div>
      <div class="col s4">
        <i class="large mdi-action-trending-up" style="color:#00838f;"></i>
        <h4 class="header">Improve</h4>
        <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
      </div>
      <div class="col s4">
        <i class="large mdi-av-equalizer" style="color:#00838f;"></i>
        <h4 class="header">Follow statistics</h4>
        <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
      </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax"><%=image_tag "img6.png"%></div>
  </div>
  <div class="section white center z-depth-2">
    <div class="row container ">
      <h2 class="header">Sign up now</h2>
      <p class="grey-text text-darken-3 lighten-3">
        <%= render 'home/signup_form' %>
      </p>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax"><%=image_tag "img8.png"%></div>
  </div>

  <footer class="page-footer cyan darken-3">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Contact</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">facebook</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">linkedin</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">github</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>



<script>
  $(document).ready(function(){
      $('.parallax').parallax();
  });
</script>