config/routes.rb
EasyGym::Application.routes.draw do

  get "profile/:id",to: "users#profile", as: "profile", path_names: { profile: 'kalle' }
  devise_for :users

  get "home/index"

  resources :workout_sessions
  resources :statistics, only: [:index]
    resources :workouts
    resources :exercises

  root :to => 'home#index'

end

app/views/layouts/_navbar.html.erb
<!-- Dropdown Structure -->
<% if user_signed_in? %>
<ul id='dropdown1' class='dropdown-content' style="margin-top: 64px;">
  <li>
    <%= link_to profile_path(current_user), style: "color: #00838f;" do %>
      <span class="mdi-hardware-keyboard-arrow-right left"></span>Profile
    <%end%>
  </li>
  <li>
    <%= link_to workout_sessions_path, style: "color: #00838f;" do %>
      <span class="mdi-hardware-keyboard-arrow-right left"></span>My sessions
    <%end%>
  </li>
  <li>
    <%= link_to workouts_path, style: "color: #00838f;" do %>
      <span class="mdi-hardware-keyboard-arrow-right left"></span>Workouts
    <%end%>
  </li>
  <li>
    <%= link_to exercises_path, style: "color: #00838f;" do %>
    <span class="mdi-hardware-keyboard-arrow-right left"></span>Exercises
    <%end%>
  </li>
  <li class="divider"></li>
  <li>
    <%= link_to statistics_path, style: "color: #00838f;" do %>
      <span class="mdi-av-equalizer left"></span>Statistics
    <%end%>
  </li>
</ul>
<% end %>

<!-- Navbar -->
<div class="navbar-fixed">
  <nav class="cyan darken-3">
    <div class="nav-wrapper">
      <%= link_to root_path do %>
        <div class="brand-logo">
          <i class="mdi-maps-directions-walk right">easy</i>
        </div>
      <% end %>
        <ul id="nav-mobile" class="right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete  %>
          </li>
          <li class="right">
            <a class='dropdown-button' href='#' data-activates='dropdown1' style="width:200px;">
              <i class="mdi-navigation-menu left"></i>
            </a>
          </li>
        <% else %>
          <li>
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
          <li>
            <%= link_to 'Sign up', new_user_registration_path%>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<html>
<head>
  <title>EasyGym</title>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= render 'layouts/navbar' %>

<!-- put this notice in modal -->
<%= notice %>
<%= alert %>

<% if current_page?('/')%>
  <%= yield %>
<% else %>
<div class="container">
  <%= yield %>
</div>
<% end %>

</body>
</html>

<script>
$(document).ready(function() {
  $('select').material_select();

  $('.modal-trigger').leanModal();
});
</script>